# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
    mysql:
        image: 'mariadb'
        ports:
            - '3408:3306'
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: laravel
            MARIADB_PASSWORD: password
            MARIADB_DATABASE: quizzer
